Update to source code preprocessing and example yamls
The main purppose of the branch is to have ability to switch between old Makefile builds and a more robust Cmake + yaml build.

However, in attempting to build several samle configs, I have found issues with the preprocessing #ifdefs throughout the code. The largest issue observed is with inconsistent (and possibly physically meaningless) ifdefs related to black holes.

This commit has some attempt to address this but I still cannot build the `CosmoConfig.yaml` variant.

An example error that is still present is

```
Users/ela017/myresearch/codes/arepo_solas/src/blackholes/bh_density.c: In function 'bh_density_evaluate':
/Users/ela017/myresearch/codes/arepo_solas/src/blackholes/bh_density.c:423:11: error: 'u' undeclared (first use in this function)
  423 |           u = r * hinv;
      |           ^
/Users/ela017/myresearch/codes/arepo_solas/src/blackholes/bh_density.c:423:19: error: 'hinv' undeclared (first use in this function)
  423 |           u = r * hinv;
      |                   ^~~~
/Users/ela017/myresearch/codes/arepo_solas/src/blackholes/bh_density.c:407:26: warning: variable 'dvz' set but not used [-Wunused-but-set-variable]
  407 |       MyDouble dvx, dvy, dvz;
      |                          ^~~
/Users/ela017/myresearch/codes/arepo_solas/src/blackholes/bh_density.c:407:21: warning: variable 'dvy' set but not used [-Wunused-but-set-variable]
  407 |       MyDouble dvx, dvy, dvz;
      |                     ^~~
/Users/ela017/myresearch/codes/arepo_solas/src/blackholes/bh_density.c:407:16: warning: variable 'dvx' set but not used [-Wunused-but-set-variable]
  407 |       MyDouble dvx, dvy, dvz;
      |                ^~~
/Users/ela017/myresearch/codes/arepo_solas/src/blackholes/bh_density.c:347:38: warning: unused variable 'wk' [-Wunused-variable]
  347 |   MyDouble h, h2, dx, dy, dz, r, r2, wk;
      |                                      ^~
/Users/ela017/myresearch/codes/arepo_solas/src/blackholes/bh_density.c: In function 'bh_density_isactive':
/Users/ela017/myresearch/codes/arepo_solas/src/blackholes/bh_density.c:473:12: error: 'Bh_Particle_Data' has no member named 'DensityFlag'
  473 |   if(BhP[n].DensityFlag < 0)
      |            ^
/Users/ela017/myresearch/codes/arepo_solas/src/blackholes/../utils/generic_comm_helpers2.h: At top level:
/Users/ela017/myresearch/codes/arepo_solas/src/blackholes/../utils/generic_comm_helpers2.h:517:12: warning: 'generic_comm_pattern_for_given_particles' defined but not used [-Wunused-function]
  517 | static int generic_comm_pattern_for_given_particles(int nactive, int indices[], void (*kernel_loc)(int, int *),
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/arepolib.dir/blackholes/bh_density.c.o] Error 1
make[1]: *** [src/CMakeFiles/arepolib.dir/all] Error 2
make: *** [all] Error 2
```

The code has unusual setup for preprocessing flags related to black holes. For example in parameters.c, there are inclusions of black hole accretion physics that exists outside of bh_active flag but this makes no sense to me. If BH_ACTIVE is not set, there shouldn't be any accretion physics.

There are also some comments in the code itself related to such questions that need to be addressed.